services:
  api:
    build: .
    container_name: titanic-backend
    ports: 
      - '8000:8000'
    networks: 
      - ai-network
  web:
    build: .
    container_name: titanic-frontend
    command: ["streamlit","run","app.py","--server.port=8501","--server.address=0.0.0.0"]
    ports: 
      - '8501:8501'
    depends_on: 
      - api
    environment: 
      - API_URL=http://api:8000/predict
    networks: 
      - ai-network

networks: 
  ai-network:
    driver: bridge